#!/usr/bin/env bun
/**
 * Build-time script: reads all files from src/templates/ and generates
 * src/generated/templates.ts with string constants.
 *
 * Replaces Go's //go:embed for template embedding.
 */

import { readdir, readFile, mkdir } from "fs/promises";
import { join, relative } from "path";

const TEMPLATES_DIR = join(import.meta.dir, "..", "src", "templates");
const OUTPUT_FILE = join(import.meta.dir, "..", "src", "generated", "templates.ts");

async function walkDir(dir: string): Promise<string[]> {
	const files: string[] = [];
	const entries = await readdir(dir, { withFileTypes: true });
	for (const entry of entries) {
		const full = join(dir, entry.name);
		if (entry.isDirectory()) {
			files.push(...(await walkDir(full)));
		} else {
			files.push(full);
		}
	}
	return files;
}

async function main() {
	const files = await walkDir(TEMPLATES_DIR);
	const entries: { key: string; content: string }[] = [];

	for (const file of files) {
		const relPath = relative(TEMPLATES_DIR, file);
		const content = await readFile(file, "utf-8");
		entries.push({ key: relPath, content });
	}

	await mkdir(join(import.meta.dir, "..", "src", "generated"), { recursive: true });

	const lines = [
		"// AUTO-GENERATED by scripts/embed-templates.ts — do not edit",
		"",
		"export const templates: Record<string, string> = {",
	];

	for (const { key, content } of entries) {
		const escaped = JSON.stringify(content);
		lines.push(`\t${JSON.stringify(key)}: ${escaped},`);
	}

	lines.push("};");
	lines.push("");

	await Bun.write(OUTPUT_FILE, lines.join("\n"));
	console.log(`Generated ${OUTPUT_FILE} with ${entries.length} templates`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
